from pydantic import BaseModel, Field
from lancedb.embeddings import get_registry
from lancedb.pydantic import LanceModel, Vector
from dotenv import load_dotenv

load_dotenv()

embedding_model = get_registry().get("gemini-text").create(name="gemini-embedding-001")

EMBEDDING_DIM = 3072

class Article(LanceModel):
    doc_id: str
    filepath: str
    filename: str = Field(description="The stem of the file name without extension")
    content: str = embedding_model.SourceField()
    embedding: Vector(EMBEDDING_DIM) = embedding_model.VectorField()

class Prompt(BaseModel):
    prompt: str = Field(description="Prompt from user, if empty consider it as missing")

class RagResponse(BaseModel):
    filename: str = Field(description="Filename of retrieved file without extension")
    filepath: str = Field(description="Absolute filepath of retrieved file")
    answer: str = Field(description="Answer generated by the LLM based on retrieved documents")
